# Generated by Django 4.2.5 on 2023-09-24 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("meal_notify", models.BooleanField(default=False)),
                (
                    "std_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Lessons",
            fields=[
                (
                    "lesson_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("lessons_name", models.CharField(max_length=255)),
                ("class_room", models.CharField(max_length=255)),
                ("lesson_hour", models.TimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="std_helper.users",
                    ),
                ),
            ],
        ),
    ]
